services:
 redis:
   image: redis
 db:
  image: postgres:9.4
 vote:
  build: ./vote
  ports:
   - 80:5000
  links:
   - redis:redis
 result:
  build: ./result
  ports:
   - 80:5001
  links:
   - db:db
 worker:
  build: ./worker
  links:
   - db:db
   - redis:redis

version: '3.0'